appiumConfig:
#  app: ""
  url: http://127.0.0.1:4723/wd/hub
  wait: 6
  capabilities:
    platformName: android
    deviceName: xxx
    appPackage: cn.futu.trader
    appActivity: cn.futu.app.main.activity.MainActivity
    unicodeKeyboard: true
    resetKeyboard: true
    noReset: true
  maxretrycount: 2

inspectConfig:
  elementInspectCount: 5
  elementInspectInterval: 1000
  activityInspectCount: 5
  activityInspectInterval: 1000